### PR TITLE
Migrate to Androidx

### LINKED ISSUE #76: Add support for Android X

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #76

### CODE REVIEW

**Comment by noties** [comment]
Hello @ZacSweers !

Thanks for the effort! I have no idea why travis build had failed, but I'm going to close this pull-request anyway. The reason is - I'm working on the next `4.0.0` release and do not want the sources of v3 & v4 to mismatch (currently there is a small mismatch already). New release will have some breaking changes (and it's not 100% backwards-compatible). So, I will put a milestone on the #76 issue to `4.0.0`. In the end now it seems finally a good time to migrate to androidx, thanks for bringing it up 🙌

**Comment by ZacSweers** [comment]
I guess I'm a little confused - now is a good time to migrate but not accepting the PR? Also - I've seen the community migrate to androidx as a minor update rather than major since the jetifier tooling handles this for consumers

**Comment by noties** [comment]
Well, the migration is indeed a minor update. As you had mentioned the jetifier handles the `com.android.support.*`, so users of androidx can use support artifacts. But not the other way around. So, as there is a big update in version 4 I decided to move the migration there (to reduce the conflicts).

**Comment by ZacSweers** [comment]
I was more confused by this line

> now it seems finally a good time to migrate to androidx

but then also closing this PR.

Regarding the rest - I'm personally of the opinion that libraries should be on androidx by now. We are almost a year on from stable jetifier, I don't think there's really a good reason to continue using support 28 and imposing the jetifier build cost (however heavily cached) on users of the library.

**Pull request closed without merging**
