### PR TITLE
added PrecomputedFutureTextSetterCompat

### PR DESCRIPTION
**Pull request by KirkBushman**
Added PrecomputedFutureTextSetterCompat with tests in the sample app.
I had to include androidx.appcompat:appcompat in deps, to do so.

Let me know what you think.

### CODE REVIEW

**Comment by KirkBushman** [comment]
I see versions are behind, are you sure you don't want me to bump those up?

for example:
gradle tools 3.5.3 -> 3.6.3
gradle wrapper 5.5.1 -> 6.2.1
build tools 28 -> 29
androidx.core 1.0.2 -> 1.2.0

**Comment by noties** [comment]
Everything seems good to me except few things:
- I do not like _no-oping_ in `PrecomputedFutureTextSetterCompat` when supplied widget is not an `AppCompatTextView`, there must be reasonable default fallback
- ~~calling `onComplete.run()` just after future is set...~~

Did you know that this _text future_ actually slow down your rendering in RecyclerView? Found this in the `AppCompatTextView`:
```java
private void consumeTextFutureAndSetBlocking() {
    if (mPrecomputedTextFuture != null) {
        try {
            Future<PrecomputedTextCompat> future = mPrecomputedTextFuture;
            mPrecomputedTextFuture = null;
            TextViewCompat.setPrecomputedText(this, future.get());
        } catch (InterruptedException | ExecutionException e) {
            // ignore
        }
    }
}
```

Calling `future.get()` on main thread whilst rendering `RecyclerView` is a bit too _googlish_ way to make things faster. I would advice not to use this feature of text-futures altogether

**Comment by KirkBushman** [comment]
> I do not like no-oping in PrecomputedFutureTextSetterCompat when supplied widget is not an AppCompatTextView, there must be the reasonable default fallback

Ok, what do you prefer?
Do we just use setText() here? or do we throw an error? 
I can make the adjustments quickly.

> Did you know that this text future actually slows down your rendering in RecyclerView?

Well, I did not look through the code or investigated this (so do not quote me), 
but I can imagine adding the threading the total computation time will get longer.
They are trying to move in the background the layout phase, and return to main before the measuring phase. I don't know if it cuts up to 90% off the main thread as I read online on their materials, but I hope they looked at this the right way.

future.get() is as heavy as the load on the function specified so I don't think it is much.
Sure having a lot of complex TextViews with spans in addition to Markwon rendering markdown I'll try to profile, with all this "on" and "off" and see. 

Tell me what you think.

**Comment by noties** [comment]
Hello @KirkBushman !

Well, calling `future.get()` is cheap _assuming_ task is done. But everything that is assumed is an option for malfunction. Imagine executor that you had passed does something weird. Or the default executor that they use gets too many tasks and  freezes. Or someone is calling this not in `RecyclerView` context. Or, hell, they change how `RecyclerView` operates ~~removing~~ enhancing how prefetch is working. And wham!, app is frozen. _Who would've thought this would happen?_ 

Anyway, let's throw an exception when method receives a `TextView` that is not a subclass of the `AppCompatTextView`, this at least seems to be a reasonable default

**Comment by KirkBushman** [comment]
> Anyway, let's throw an exception when method receives a TextView that is not a subclass of the AppCompatTextView, this at least seems to be a reasonable default.

Here it is, tell me if anything else needs to be done.

**Pull request merged**
