### PR TITLE
Replaced custom SpannableBuilder with ReverseSpannableStringBuilder

### PR DESCRIPTION
**Pull request by c-b-h**
Background:
The usage and maintaining of SpannableBuilder is reduced by using
a good-old-SpannableStringBuilder directly but making sure its spans are
reversed.

The implementation is credited Uncodin/bypass

### CODE REVIEW

**Comment by noties** [comment]
Hello @c-b-h ! Would you care to mention why such a change is required/desired? Because I do not see the case yet

**Comment by c-b-h** [comment]
I'm in the process of adding some new features to to `library-view` and `SpannableMarkdownVisitor` and instead of having the need to manage a custom span builder I feel it's easier to work with an "almost" exact version as the system's `SpannableStringBuilder`.

Also if you look at the code you will notice that the code becomes a lot less complex.

Feel free to reject if you don't feel this adds value to the **master** code, which I must say is a very nicely architected library 👍 .

**Comment by noties** [comment]
Hello @c-b-h !

I have no special attachment to `SpannableBuilder`, but there are 2 things to consider:
* How performance is affected by reversing span array with each `getSpans` call? Did you make any measurements?
* There was an issue with empty lines at the end of parsed markdown. New empty lines were added even if markdown contained only one line. Although I think that it's not the responsibility of SpannableBuilder still, it is a use case. (I think it should be done by visitor by checking if more nodes are present, so new lines would be added only as separators between nodes, so if we agree on moving to different implementation of SpannableBuilder we can address that also).

Also, I see another commit. I do like very much idea of span factory. But if you please can you make a different pull request with this functionality because there are some things to consider and they do not belong to the migration to different SpannableBuilder (mainly you missed html (which also constructs spans) but it can be added for sure).

And also can you please issue your pull requests to `v1.1.0` branch? I have just created it for the next release (with syntax highlight, yay!) and think that your changes can be included

Thanks 🙌

**Comment by noties** [comment]
BTW @c-b-h current development branch `v1.1.0` has spannable factory abstraction. if you want you can check it out

**Comment by noties** [comment]
Hey @c-b-h ! I'm going to close this PR now. I have added the `SpannableFactory` abstraction to the master branch now. If you still interested in migration `SpannableBuilder` -> `SpannableStringBuilder` let's create a new issue and discuss it there.

🙌

**Comment by c-b-h** [comment]
Sorry... been on vacation and away from computers and work-related errands.

I will consider your two points and get back with a new request.

**Comment by c-b-h** [comment]
@noties ... Could you please elaborate on whether
>There was an issue with empty lines at the end of parsed markdown
applies to all markdown or just `TableCell`s

My change request contained the same removal mechanism originally implemented inside `SpannableBuilder`.

**Comment by noties** [comment]
@c-b-h I mean [this](https://github.com/noties/Markwon/blob/7c7b1f59a83f721d49a9b323efa151d37e322b28/library/src/main/java/ru/noties/markwon/SpannableBuilder.java#L163-L179) piece of logic. It applies to the whole markdown (tables using `removeFromEnd` method for different purpose -> to remove spans from main builder and pass them to `TableRowSpan` which renders contents by its own means). But as I said there must be a different way to do it (like inspecting nodes and decide whether or not a new line should be added)

**Comment by c-b-h** [comment]
@noties Could you provide me a (small) sample of of Markdown markup that is parsed with redundant white space characters? I would use that for trying out the changes I make.

**Comment by noties** [comment]
@c-b-h well, all the text actually (easy to check just comment out the lines that I had linked in previous comment). For example this:
* `# Header`
* `Just a text (no even markdown!)`

**Comment by c-b-h** [comment]
@noties 

For the paragraph 
> Just a text (no even markdown!)

you add breaks both [here](https://github.com/noties/Markwon/blob/master/library/src/main/java/ru/noties/markwon/renderer/SpannableMarkdownVisitor.java#L389) and [here](https://github.com/noties/Markwon/blob/master/library/src/main/java/ru/noties/markwon/renderer/SpannableMarkdownVisitor.java#L392).

For the header
> Header

you add breaks [here](https://github.com/noties/Markwon/blob/master/library/src/main/java/ru/noties/markwon/renderer/SpannableMarkdownVisitor.java#L251) and [here](https://github.com/noties/Markwon/blob/master/library/src/main/java/ru/noties/markwon/renderer/SpannableMarkdownVisitor.java#L254).

Why is that?

**Comment by c-b-h** [comment]
@noties 
With experience from another library I would prefer that line breaks are added when actually stated in the markdown as hard lines meaning that if I really want an extra break after my heading, then I need to explicitly add that in the markup. The way it is implemented I will get lines even though I don't want them; for my purpose I will use an implementation of [LineHeightSpan](https://developer.android.com/reference/android/text/style/LineHeightSpan) to make the headings have extra space below.

**Pull request closed without merging**
